### ISSUE TITLE
Download button is available before rendering

### ISSUE THREAD

**Issue by rileysommerville** [rileysommerville/microbit-export#9]
Currently, the download button is available before any blocks have been rendered, causing the page to hang.

Update the download button to remain unavailable until blocks have been rendered.

**Comment by saraogipraveen** [comment]
Hi @rileysommerville, I can take this up.

**Comment by rileysommerville** [comment]
Thanks for your work on this, @saraogipraveen. I did mean to switch the button to 'disabled', which you've done 👍

The second case you mentioned is a good one to consider. I'm closing this issue, but #14 will cover that case.
